name: Nuget
on:
  push:
    branches:
      - 'main'       # Run the workflow when pushing to the main branch
    paths:
      - 'src/**'
      - '.github/**'
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests
env:
  outDir: out
  projectPath: 'src/Jarc/Jarc.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Restore dependencies
      run: dotnet restore ${{ env.projectPath }}

    - name: Build
      run: dotnet build ${{ env.projectPath }} --no-restore

    - name: Test
      run: dotnet test tests/Jarc.UnitTests/Jarc.UnitTests.csproj --verbosity normal
    
    - name: Package
      run: dotnet pack ${{ env.projectPath }} -c Release -o ${{ env.outDir }} --no-restore --no-build

    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.outDir }}/*.nupkg

  deploy:
    environment: Jarc
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download the NuGet package created in the previous job
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ${{ env.outDir }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Set tag
        run: nbgv tag

      - name: Publish NuGet package
        run: dotnet nuget push ${{ env.outDir }}/*.nupkg --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate